steps:
  # Install dependencies for client
  - name: gcr.io/cloud-builders/npm
    args: [install]
  # Build client
  - name: gcr.io/cloud-builders/npm
    args: [run-script, build]
  # Install dependencies for server
  - name: gcr.io/cloud-builders/npm
    args: [install]
    dir: ./server
  # Build server
  - name: gcr.io/cloud-builders/npm
    args: [run-script, build]
    dir: ./server
  # Decrypt firestore credentials
  - name: gcr.io/cloud-builders/gcloud
    args:
      [
        kms,
        decrypt,
        --location=global,
        --keyring=timetable-client-auth,
        --key=timetable-kosimst-client-credentials,
        --plaintext-file=credentials/client-auth.json,
        --ciphertext-file=credentials/client-auth.json.encrypted,
      ]
    dir: ./server/services/updateTimetable
  # Deploy app
  - name: gcr.io/cloud-builders/gcloud
    args: [app, deploy, '${_APPNAME}']
    dir: ./server
  # Install dependencies for update-timetables service
  - name: gcr.io/cloud-builders/npm
    args: [install]
    dir: ./server/services/updateTimetable
  # Build update-timetables service
  - name: gcr.io/cloud-builders/npm
    args: [run-script, build]
    dir: ./server/services/updateTimetable
  # Deploy update-timetables service
  - name: gcr.io/cloud-builders/gcloud
    args: [app, deploy, '${_APPNAME}']
    dir: ./server
